---
title: test-site-snipcart
timezone: UTC
url: ''
snipcart_api_key: ''
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: product
  values:
    layout: product
    permalink: "/products/:title"
    name: ''
    sku: ''
    image: ''
    weight: 0.0
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
